### ISSUE TITLE
프로젝트 기본 설정

### ISSUE THREAD

**Issue by Yisak5** [HwangJunha/tdd#16]
프로젝트 기본 설정
- [ ] vo 패키지 하위에 entity, request, response 패키지 생성
- [x] GlobalExceptionHandler 생성
- [x] ApiResponse, ErrorResponse GPT 코드리뷰 반영

**Comment by suea724** [comment]
ApiResponse, ErrorResponse 반영 완료되었습니다.
- PR 링크 : https://github.com/HwangJunha/tdd/pull/17

**Comment by suea724** [comment]
GlobalExceptionHandler config 브랜치 작업 완료하였습니다.
